bouraka-django/bouraka/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from bouraka import views

urlpatterns = [
        url(r'^admin/', include(admin.site.urls)),
        url(r'^home/', 'bouraka.views.home'),
        url(r'^accomplishments/elec/', 'bouraka.views.elec'),
        url(r'^accomplishments/roues/', 'bouraka.views.roues'),
        url(r'^accomplishments/moteur/', 'bouraka.views.moteur'),
        url(r'^accomplishments/simulateur/', 'bouraka.views.simulateur'),
        url(r'^history/', 'bouraka.views.history'),
        url(r'^shell/', 'bouraka.views.shell'),
        url(r'^educeco/', 'bouraka.views.educeco'),
        url(r'^michelin/', 'bouraka.views.michelin'),
        url(r'^futur/', 'bouraka.views.futur'),
        url(r'^envol/', 'bouraka.views.envol'),
        url(r'^epic/', 'bouraka.views.epic'),
        url(r'^orca/', 'bouraka.views.orca'),
        url(r'^contacts/', 'bouraka.views.contacts'),

        url(r'^actualites/', include('news.urls')),
        url(r'^team/', include('members.urls')),
        url(r'^sponsors/', include('sponsors.urls')),
        url(r'^results/', include('results.urls')),

        url(r'^$', 'bouraka.views.home'),
]

bouraka-django/members/urls.py
from django.conf.urls import patterns, url
from members import views

urlpatterns = patterns('',
  url(r'^$', views.index, name='index'),
)

bouraka-django/news/urls.py
from django.conf.urls import patterns, url
from news import views

urlpatterns = patterns('',
		url(r'^$', views.index, name='index'),
)

bouraka-django/results/urls.py
from django.conf.urls import patterns, url
from results import views

urlpatterns = patterns('',
  url(r'^$', views.index, name='index'),
)

bouraka-django/sponsors/urls.py
from django.conf.urls import patterns, url
from sponsors import views

urlpatterns = patterns('',
  url(r'^$', views.index, name='index'),
)

bouraka-django/members/models.py
from django.db import models

class Member(models.Model):
    name = models.CharField( max_length = 150, blank = True )
    title = models.CharField( max_length = 150, blank = True )
    team = models.CharField( max_length = 150, blank = True )
    department = models.CharField( max_length = 150, blank = True  )
    year = models.IntegerField( blank = True )
    description = models.TextField( blank = True )
    photo = models.ImageField( upload_to = 'members' )
    order = models.IntegerField()
    def __str__(self):
        return self.name

bouraka-django/news/models.py
from django.db import models
import datetime

class News(models.Model):
  title = models.CharField(max_length = 150)
  text = models.TextField();
  publication_date = models.DateTimeField('published on:', default=datetime.datetime.now)
  def __str__(self):
    return self.title

class NewsImage(models.Model):
  news = models.ForeignKey(News)
  image = models.ImageField()

bouraka-django/results/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Result(models.Model):
  year = models.PositiveIntegerField(validators=[MinValueValidator(1900),MaxValueValidator(2200)])
  description = models.TextField(max_length = 500)
  def __str__(self):
    return str(self.year)

bouraka-django/slides/models.py
from django.db import models

class Slide(models.Model):
  title = models.CharField(max_length = 150)
  def __str__(self):
    return self.title

class SlideImage(models.Model):
  slide = models.ForeignKey(Slide)
  image = models.ImageField()

bouraka-django/sponsors/models.py
from django.db import models

class Sponsor(models.Model):
    name = models.CharField( max_length = 150, blank = True )
    group = models.CharField( max_length = 150, blank = True )
    website = models.URLField( max_length = 150, blank = True )
    description = models.TextField( blank = True )
    logo = models.ImageField( upload_to = 'sponsors' )
    order = models.IntegerField()
    def __str__(self):
        return self.name

bouraka-django/bouraka/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import RequestContext, loader
from news.models import News
from slides.models import Slide
from django.http import HttpResponseRedirect

def home(request):
    latest_news_list = News.objects.order_by('-publication_date')[:4]
    try:
         slide = Slide.objects.get(title='home')
    except Slide.DoesNotExist:
        slide = None
    template = loader.get_template('bouraka/home.html')
    context = {
            'latest_news_list': latest_news_list,
            'slide': slide,
    }
    return render(request, 'bouraka/home.html', context)

def gallery(request):
    return render(request, 'bouraka/gallery.html')
def history(request):
    return render(request, 'bouraka/history.html')
def team(request):
    return render(request, 'bouraka/team.html')
def shell(request):
    return render(request, 'bouraka/shell.html')
def educeco(request):
    return render(request, 'bouraka/educeco.html')
def michelin(request):
    return render(request, 'bouraka/michelin.html')
def futur(request):
    return render(request, 'bouraka/futur.html')
def envol(request):
    return render(request, 'bouraka/envol.html')
def epic(request):
    return render(request, 'bouraka/epic.html')
def orca(request):
    return render(request, 'bouraka/orca.html')
def elec(request):
    return render(request, 'bouraka/elec.html')
def roues(request):
    return render(request, 'bouraka/roues.html')
def moteur(request):
    return render(request, 'bouraka/moteur.html')
def simulateur(request):
    return render(request, 'bouraka/simulateur.html')
def accomplishments(request):
    return render(request, 'bouraka/accomplishments.html')
def contacts(request):
    return render(request, 'bouraka/contacts.html')

bouraka-django/members/views.py
from django.shortcuts import render
from members.models import Member

def index(request):
    members_list = Member.objects.order_by('order')
    teams_list = []
    for member in members_list:
        if member.team not in teams_list:
            teams_list.append(member.team)
    teams_list.sort()
    template = 'members/members.html'
    context = { 'members_list': members_list, 'teams_list': teams_list }
    return render(request, template, context)

bouraka-django/news/views.py
from django.shortcuts import render
from news.models import News

def index(request):
  news_list = News.objects.order_by('-publication_date')
  template = 'news/news.html'
  context = { 'news_list': news_list }
  return render(request, template, context)

bouraka-django/results/views.py
from django.shortcuts import render
from results.models import Result

def index(request):
    results_list = Result.objects.order_by('-year')
    template = 'results/results.html'
    context = { 'results_list': results_list }
    return render(request, template, context)

bouraka-django/slides/views.py
from django.shortcuts import render
from slides.models import Slide

def index(request, slide_name):
  slide = Slide.objects.get(title=slide_name)
  template = 'slide/home.html'
  context = { 'slide': slide }
  return render(request, template, context)

bouraka-django/sponsors/views.py
from django.shortcuts import render
from sponsors.models import Sponsor

def index(request):
    sponsors_list = Sponsor.objects.order_by('order')
    groups_list = []
    for sponsor in sponsors_list:
        if sponsor.group not in groups_list:
            groups_list.append(sponsor.group)
    groups_list.sort()
    template = 'sponsors/sponsors.html'
    context = { 'sponsors_list': sponsors_list, 'groups_list': groups_list }
    return render(request, template, context)

bouraka-django/members/templates/members/members.html
{% extends "bouraka/base.html" %}
{% load staticfiles %}

{% block imports %}
{% endblock %}

{% block content %}
<div class="container" style="padding-left:10%;padding-right:10%;" >
  <div class="row">
    <div class="col-xs-12">
      <h1 style='text-align:center;'> L’équipe du PIC </h1><br>
    </div>
  </div>
  {% for team in teams_list %}
  <hr style="width:100%;" />
  <div class="row" style="margin-bottom:3%" >
    <div class="col-xs-12">
      <h2 >{{ team  }}</h2>
    </div>
  </div>
  {% for member in members_list %}
  {% if member.team == team %}
  <div class="row" style=" margin-top:2%">
		<div class="col-xs-2" >
			<img  style="width:100%;" src="/media/{{ member.photo }}" alt="Not Rendered">
		</div>
			<div class="col-xs-10">
				<p>
				<h3>{{ member.name }}</h3>
				<p><b>{{ member.title }}</b></p>
				<p>{{ member.year }}ème année au département {{ member.department  }} - INSA Lyon</p>
				<p> {{ member.description }}</p>
			</div>
	</div>
	{% endif %}
	{% endfor %}
{% endfor %}
</div>
{% endblock %}

bouraka-django/news/templates/news/news.html
{% extends "bouraka/base.html" %}
{% load staticfiles %}

{% block imports %}
<!-- Custom CSS -->
<link href="{% static 'css/elec.css' %}" rel="stylesheet">
<!-- Custom CSS -->
<link href="{% static 'css/history.css' %}" rel="stylesheet">
<!-- Custom Fonts -->
<link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<div class="container marketing">
	{% if news_list %}
	<ul>
		{% for news in news_list %}
		<hr class="featurette-divider">
		<div class="row featurette">
			<div class="section">
				<div class="col-md-9 col-md-offset-1">
					<span id="{{ news.title }}" class="anchor"></span>
					<h2 class="text-primary">{{ news.title }}</h2>
					<span class="text-muted"><i>Date de publication: </i>{{ news.publication_date }}<br><br></span>
					<p align="justify">{{ news.text | safe }}</p>
					{% if news.newsimage_set.all %}
					<div id="{{ news.publication_date }}{{ news.name }}" class="links">
						{% for image in news.newsimage_set.all %}
						<a href="/media/{{ image.image }}" title="">
							<img src="/media/{{ image.image }}" style="width:10%;" alt="Not rendered">
						</a>
						{% endfor %}
					</div>
					<script>
document.getElementById("{{ news.publication_date }}{{ news.name }}").onclick = function (event) {
	event = event || window.event;
	var target = event.target || event.srcElement,
	link = target.src ? target.parentNode : target,
		options = {index: link, event: event},
		links = this.getElementsByTagName('a');
	blueimp.Gallery(links, options);
};
					</script>
					{% endif %}
				</div>
			</div>
		</div>
		{% endfor %}
		<hr class="featurette-divider">
	</ul>
	{% else %}
	<p>No news are available.</p>
	{% endif %}
</div>
{% endblock %}

{% block footer %}
<div class="banner">
	<div class="container">
		<div class="row">
			<div class="col-lg-6">
				<h2>The story goes on:</h2>
			</div>
			<div class="col-lg-6">
				<ul class="list-inline banner-social-buttons">
					<li>
						<a href="https://www.facebook.com/ProtoINSAClub" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
					</li>
					<li>
						<a href="https://www.youtube.com/user/ProtoINSAClub" class="btn btn-default btn-lg"><i class="fa fa-youtube fa-fw"></i> <span class="network-name">Youtube</span></a>
					</li>
					<li>
						<a href="https://twitter.com/InsaProto" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">twitter</span></a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
{{ block.super }}
{% endblock %}

bouraka-django/results/templates/results/results.html
{% extends "bouraka/base.html" %}
{% load staticfiles %}

{% block imports %}
<!-- Custom Fonts -->
<link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
{% endblock %}

{% block blueimp %}
{% endblock %}

{% block content %}
<div class="container" style="padding-left:15%;padding-right:15%;font-size:120%" >
<h2 align=center>Temps forts et résultats</h2> </br>

{% for result in results_list %}
<b>{{ result.year }}</b></br>
{{ result.description }}</br></br>
{% endfor %}

</div>
{% endblock %}

bouraka-django/sponsors/templates/sponsors/sponsors.html
{% extends "bouraka/base.html" %}
{% load staticfiles %}

{% block imports %}
{% endblock %}

{% block content %}
<div class="container" style="font-size:120%;">
	<div class="row">
		<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
			<div class="row">
				<div class="col-xs-12">
					<h1 style='text-align:center;'> Sponsors </h1>
				</div>
			</div>

			<hr style="width:100%;" />  <!-- ********************************************** -->
			<p align="justify">Nous tenons à remercier l'ensemble de nos partenaires, sans qui le Proto Insa Club ne pourrait être ce qu'il est aujourd'hui !</p>
			<p align="justify">C'est grâce à un support sous différentes formes (aide matérielle, conseils et aide dans les services, contribution financière...) que le PIC peut ainsi continuer à évoluer parmi le Top 10 des équipes Européennes.</p>


			{% for group in groups_list %}
			<hr style="width:100%;" />  <!-- ********************************************** -->

			<div class="row" style="margin-bottom:3%" >
				<div class="col-xs-8">
					<h2>{{ group }}</h2>
				</div>
			</div>

			<hr style="width:100%;" />  <!-- ********************************************** -->

			{% for sponsor in sponsors_list %}
			{% if sponsor.group == group %}
			<div class="row" style=" margin-top:3%">
			<div class="col-xs-4" >
				<img  style="width:100%;" src="/media/{{ sponsor.logo }}" alt="Not Rendered">
			</div>
				<div class="col-xs-8">
					<p align=right>
					{{ sponsor.name }}<br/>
					<a href={{ sponsor.website }}>{{ sponsor.website }}</a><br/>
					{{ sponsor.description }}<br/>
					</p>
				</div>
		</div>
		{% endif %}
		{% endfor %}
		{% endfor %}
	</div>



	{% endblock %}

bouraka-django/templates/bouraka/accomplishments.html
{% extends "bouraka/base.html" %}
{% load staticfiles %}

{% block imports %}
<!-- Custom CSS -->
<link href="{% static 'css/accomplishements.css' %}" rel="stylesheet">
<!-- Custom Fonts -->
<link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
<!-- {{ block.super }} -->
{% endblock %}


{% block content %}
<h1> Accomplishements </h1>    <!-- START /.content-section-a -->
    <div class="content-section-a">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <!-- <hr class="section-heading-spacer"> -->
                    <div class="clearfix"></div>
                    <h2 class="section-heading">1992-1995 : Beginnings with ENVOL</h2>
                    <p class="lead" align="justify">In 1992, the first vehicle is designed and built by the team PIC, and is named « ENVOL ». After several years devoted to its development, the prototype succeeds to reach a record of 365 km/L on the Castelet circuit, in 1995.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="{% static 'images/envol.jpg' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- END /.content-section-a -->


    <!-- START /.content-section-b -->
    <div class="content-section-b">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <!-- <hr class="section-heading-spacer"> -->
                    <div class="clearfix"></div>
                    <h2 class="section-heading">1996-2000 : 2nd prototype ORCA</h2>
                    <p class="lead" align="justify">Between 1995 and 1996, the new rules of the competition require the team to design a new prototype. Thanks to technological advances, the team develops "ORCA" by using mainly of carbon fiber. In addition, work on aerodynamics makes his appearance change dramatically from the previous prototype. A new engine is also designed to reduce consumption.Thus, ORCA is lighter, and therefore more efficient than its predecessor, and in 2000 he established his own record with a performance of 990 km/L on the Nogaro circuit, in France.</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="{% static 'images/orca2.jpg' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- END /.content-section-b -->

    <!-- START /.content-section-a -->
    <div class="content-section-a">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <!-- <hr class="section-heading-spacer"> -->
                    <div class="clearfix"></div>
                    <h2 class="section-heading">2004-2005 : Design of the prototype « EPIC » </h2>
                    <p class="lead" align="justify">In 2004, the team seizes a great opportunity. Taking advantage of an offer from Eurocopter, the PIC was able to acquire one of the seven hulls prototype (named « TED ») that the company built to present them at the Shell Eco Marathon. The work to be done to transform a single-hull into an eligible to compete vehicle is huge. But this year, the team reached a membership of 40 members for the first time, and motivation is at its peak.
                    Lots of points had been called into question, as the engine, the chassis, the onboard electronic and the calculator…that is to say that the team was left virtually to zero. After 8 moths of hard work, the PIC decided to run the Educ’Eco at Nogaro (France). With a new car and virtually untested, the team managed to achieve a surprising result for the first round of EPIC, with a performance of 1348 km/ L, placing it to the 17th place in the overall standings ! What is more, the team wrote a record of the behavior of ball bearings depending on the preload and the type of lubrication. This file was awarded the first prize of National Education ! This folder will be followed in 2005-2006 by a battery of tests carried out in partnership with a laboratory of the INSA Lyon.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="{% static 'images/Epic2010.jpg' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- END /.content-section-a -->

    <!-- START /.content-section-b -->
    <div class="content-section-b">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <!-- <hr class="section-heading-spacer"> -->
                    <div class="clearfix"></div>
                    <h2 class="section-heading">2005-2006 : Second participation of EPIC</h2>
                    <p class="lead" align="justify">The performance of the prototype in the previous season showed his potential. The objectives were therefore to improve reliability and to avoid the problems encountered, as engine sensors deficient, some electronic problems, a big problem with chain (multiple derailments), and even problems with compressed air. For the second participation of EPIC at the Shell Eco Marathon, reliability goals to earn places in the rankings were made ! The prototype validated the four runs allowed, and improved performance each time to reach 1829 km/ L ! The last run has earned us a 10th position on 258 participants overall, a 5th place in gasoline, and an 8th place in the student ranking. Alongside the competition, that year the PIC presented two folders : one on a simulator for the Technical Innovation Award, and one for the price of Communications. These awards are designed to highlight something other than the performance of the prototype, and the simulator was one of the great surprises and attractions during the race. It allows anyone to take the position of the EPIC pilot and run virtually laps in Nogaro. It has received the Special Mention of the Jury Technical Innovation. However, the team still had work regarding communication…</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="{% static 'images/2005.jpg' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- END /.content-section-b -->

    <!-- START /.content-section-a -->
    <div class="content-section-a">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <!-- <hr class="section-heading-spacer"> -->
                    <div class="clearfix"></div>
                    <h2 class="section-heading">2012-2013 : Best Result ever in Rotterdam</h2>
                    <p class="lead" align="justify">Work in progress ...</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- END /.content-section-a -->

    <!-- START /.content-section-b -->
    <div class="content-section-b">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <!-- <hr class="section-heading-spacer"> -->
                    <div class="clearfix"></div>
                    <h2 class="section-heading">2013-2014 : Last season for EPIC</h2>
                    <p class="lead" align="justify">Work in progress ...</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- END /.content-section-b -->

    <!-- START /.content-section-a -->
    <div class="content-section-a">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <!-- <hr class="section-heading-spacer"> -->
                    <div class="clearfix"></div>
                    <h2 class="section-heading">2014-2015 : Design of a new vehicule</h2>
                    <p class="lead" align="justify">Work in progress ...</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- END /.content-section-a -->
{% endblock %}

{% block footer %}
    <div class="banner">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h2>The story goes on :</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="https://www.facebook.com/ProtoINSAClub" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
                        </li>
                        <li>
                            <a href="https://www.youtube.com/user/ProtoINSAClub" class="btn btn-default btn-lg"><i class="fa fa-youtube fa-fw"></i> <span class="network-name">Youtube</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {{ block.super }}

{% endblock %}

bouraka-django/templates/bouraka/home.html
{% extends "bouraka/base.html" %}
{% load staticfiles %}

{% block blueimp %}
<!-- The Gallery as lightbox dialog, should be a child element of the document body 
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
  <div class="slides"></div>
  <h3 class="title"></h3>
  <a class="prev">‹</a>
  <a class="next">›</a>
  <a class="close">×</a>
  <a class="play-pause"></a>
  <ol class="indicator"></ol>
</div> -->

<div class="container">
  <div class="row">
    <div class="col-md-3 "> <!---->
      <h3 class="form-signin-heading">Actualités</h3>
        <section class="panel panel-default">
          <div class="panel-body">
            {% if latest_news_list %}
            <ul>
            {% for news in latest_news_list %}
              <li><h4><a href="/actualites/#{{ news.title }}">{{ news.title }}</a></h4></li>
            {% endfor %}
            </ul>
            {% else %}
            <p>No news are available.</p>
            {% endif %}
          </div>
        </section>
    </div>

    <div class="col-md-6">
      <!-- The Gallery as inline carousel, can be positioned anywhere on the page -->
      <div id="blueimp-gallery-carousel" class="blueimp-gallery blueimp-gallery-carousel">
        <div class="slides"></div>
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol> 
      </div>
      <!-- list of pictures to display -->
      <div id="links" class="links">
        {% if slide %}
          {% if slide.slideimage_set.all %}
            {% for image in slide.slideimage_set.all %}
              <a href="/media/{{ image.image }}" title=""></a>
            {% endfor %}
          {% endif %}
        {% endif %}
      </div>
      <br>
    </div>
    <div class="col-md-3">
      <!-- <h3 class="form-signin-heading">Abonnement à la newsletter</h3>
      <form id="login_form" method='post' action='/newsletter/subscribe_default/'> {% csrf_token %}
        <br>
        <button class="btn btn-sm btn-primary btn-block" type="submit" name="subscribe">S'abonner</button>
        <br>
        <button class="btn btn-sm btn-primary btn-block" type="submit" name="unsubscribe">Se désabonner</button>
				</form>
				<br> -->
					<br>
        <h3 class="form-signin-heading">Suivez-nous sur :</h3>
        <div>
					<br>
					<h4> Facebook </h4><a href="https://www.facebook.com/ProtoINSAClub"><i class="fa fa-facebook-square" style="font-size: 44px;"></i></a>
					<h4> YouTube </h4><a href="https://www.youtube.com/user/ProtoINSAClub"><i class="fa fa-youtube-play" style="font-size: 44px;"></i></a>
					<h4> Twitter </h4><a href="https://twitter.com/InsaProto"><i class="fa fa-twitter" style="font-size: 44px;"></i></a>
        </div>
    </div>
  </div>
</div>

{% endblock %}

{% block content %}

<!-- Marketing messaging and featurettes -->
<!-- Wrap the rest of the page in another container to center all the content. -->
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <a href="http://www.insa-lyon.fr/">
        <img class="img-circle center-block" src="{% static 'images/home/insa.jpg' %}" style="width:39.2%;" alt="Not Rendered">
      </a>
      <h2><p class="text-center">Notre Ecole</p></h2>
      <p align="justify"> L'INSA de Lyon est une des grandes écoles d'ingénieurs françaises, pluridisciplinaire et internationale au cœur de l'Europe. Elle forme des ingénieurs pluri-compétents, humanistes, innovants et dotés d'un esprit entrepreneurial.</p>
    </div>
    <div class="col-md-4">
      <a href="http://www.shell.com/global/environment-society/ecomarathon/events/europe.html">
        <img class="img-circle center-block" src="{% static 'images/home/shell.jpg' %}" style="width:39.2%;" alt="Not Rendered">
      </a>
      <h2><p class="text-center">Le Shell Eco-marathon</p></h2>
      <p align="justify">Le SEM est une compétition internationale où plus de 200 équipes d'étudiants du monde entier s'affrontent pour concevoir, construire et faire courir des véhicules à ultra faible consommation d'énergie. Avec 50000 visiteurs annuels, c'est un évènement unique qui suscite le débat sur ​​l'avenir de la mobilité, inspirant les jeunes ingénieurs à repousser les limites de l'efficacité énergétique.</p>
    </div>
    <div class="col-md-4">
      <a href="/sponsors/">
        <img class="img-circle center-block" src="{% static 'images/home/sponsors.png' %}" style="width:39.2%;" alt="Not Rendered">
      </a> 
      <h2><p class="text-center"> Nos Sponsors </p></h2>
      <p align="justify">Plusieurs entreprises, organisations et associations nous aident à faire évoluer notre prototype chaque année. Nous les remercions sincèrement et nous espérons que notre partenariat se poursuivra pour les années à venir.</p>
    </div>
  </div> 
</div>
{% endblock %}

bouraka-django/templates/bouraka/moteur.html
{% extends "bouraka/base.html" %}
{% load staticfiles %}

{% block imports %}
<!-- Custom Fonts -->
<link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
{% endblock %}


{% block content %}
<h3 align=center style="color:red"> EN CONSTRUCTION... </h3>
{% endblock %}